from . import applicant_education
from . import applicant_experience_job
from . import applicant_partner
from . import country
from . import hr_applicant
from . import applicant_famility
from . import applicant_personal_reference
from . import applicant_medical
from . import generar_reporte
from . import hr_footer