{
    "name": "Transcash Retail Commissions",
    "summary": "Liquidación de comisiones desde ventas sincronizadas con maestros automáticos",
    "version": "18.0.2.0.0",
    "category": "Sales/Commissions",
    "author": "Transcash",
    "license": "LGPL-3",
    "depends": ["base"],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        "security/commission_security.xml",
        "security/ir.model.access.csv",
        "data/commission_sequence.xml",
        "data/commission_cron.xml",
        "views/commission_master_views.xml",
        "views/commission_rule_views.xml",
        "views/commission_sale_views.xml",
        "views/commission_sync_views.xml",
        "views/commission_period_views.xml",
        "views/commission_settlement_views.xml",
        "views/res_config_settings_views.xml",
        "views/commission_menus.xml",
    ],
    "application": True,
    "installable": True,
}
