{
    "name": "Control de Caja Chica",
    "version": "18.0.3.0.0",
    "summary": "Fondos, gastos, aprobaciones, liquidaciones y devoluciones de caja chica",
    "category": "Operations",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": ["base", "mail", "web", "hr"],
    "data": [
        "security/petty_cash_security.xml",
        "security/ir.model.access.csv",
        "data/petty_cash_sequence.xml",
        "views/petty_cash_category_views.xml",
        "views/res_partner_views.xml",
        "views/hr_department_views.xml",
        "views/petty_cash_box_views.xml",
        "views/petty_cash_fund_views.xml",
        "views/petty_cash_settlement_views.xml",
        "views/petty_cash_expense_views.xml",
        "wizard/petty_cash_report_wizard_views.xml",
        "report/petty_cash_reports.xml",
        "views/petty_cash_menus.xml",
    ],
    "application": True,
    "installable": True,
}
