{
    "name": "Recruitment EC - Contratos y Décimos",
    "summary": "Genera automáticamente contrato, solicitudes de décimos, ficha y borrador de correo al contratar",
    "version": "18.0.1.1.0",
    "category": "Human Resources/Recruitment",
    "author": "Custom Development",
    "license": "LGPL-3",
    "depends": [
        "hr_recruitment",
        "hr_contract",
        "mail",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/default_templates.xml",
        "views/document_template_views.xml",
        "views/onboarding_config_views.xml",
        "views/benefit_request_views.xml",
        "views/onboarding_package_views.xml",
        "views/hr_applicant_views.xml",
        "views/hr_contract_views.xml",
        'views/employee_views.xml',
        'views/company_views.xml',
        'views/payroll_authorization.xml',
        'views/reglamento_interno_views.xml',
        'views/document_variable.xml',
        'views/hr_ec_document_variable_views.xml',
        "report/report_actions.xml",
        "report/report_templates.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "hr_recruitment_ec_contract/static/js/document_variable_drag.js",
            "hr_recruitment_ec_contract/static/xml/document_variable_drag.xml",
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
