{
    "name": "Recruitment EC - Contratos y Décimos",
    "summary": "Genera automáticamente contrato, solicitudes de décimos, ficha y borrador de correo al contratar",
    "version": "18.0.1.1.0",
    "category": "Human Resources/Recruitment",
    "author": "Custom Development",
    "license": "LGPL-3",
    "depends": [
        "hr_recruitment",
        "hr_contract",
        "mail",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/default_templates.xml",
        "views/document_template_views.xml",
        "views/onboarding_config_views.xml",
        "views/benefit_request_views.xml",
        "views/onboarding_package_views.xml",
        "views/hr_applicant_views.xml",
        "views/hr_contract_views.xml",
        "report/report_actions.xml",
        "report/report_templates.xml",
        "views/menu_views.xml",
    ],
    "assets": {},
    "application": True,
    "installable": True,
    "auto_install": False,
}
